name: skills_tool
permissions:
  contents: read

on:
  # Run CI on all PRs (against any branch) and on pushes to the main branch.
  pull_request:
    paths:
      - '.github/workflows/skills_tool.yaml'
      - 'pubspec.yaml'
      - 'skills/**'
      - 'tool/generator/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/skills_tool.yaml'
      - 'pubspec.yaml'
      - 'skills/**'
      - 'tool/generator/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: tool/generator

jobs:
  analyze_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
        with:
          sdk: stable

      - run: dart pub get
      
      - run: dart analyze --fatal-infos

      - run: dart test

  formatting_stable_ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
        with:
          sdk: stable

      - run: dart pub get
      
      - run: dart format --output=none --set-exit-if-changed .
